name: Sync Fork

on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: RPi-Distro
          base: master
          head: master
